name = "ac-selling-dashboard"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }

